# We will use python 3.6 for our image
FROM python:3.6

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN wget http://aber-owl.net/aber-owl/diseasephenotypes/ontology/embeddings-data.tar.gz
RUN tar xvzf embeddings-data.tar.gz

# Launch in Juyter notebook

# docker run -i -t -p 8888:8888 -c "jupyter notebook --notebook-dir=/usr/src/app/ --ip='0.0.0.0' --port=8888 --no-browser --allow-root"